### ISSUE TITLE
Systems architecture planning

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/best-evidence#11]
Systems architecture planning

**Comment by nelsonic** [comment]
@markwilliamfirth guessing this is a "_holding_" issue for now? 
![image](https://user-images.githubusercontent.com/194400/28267565-87e0b398-6af2-11e7-8a3f-d737fb8ee2bd.png)
(_please add description and/or checklist of what's required from me. thanks!_)

**Comment by SimonLab** [comment]
The application is currently running with Elixir, Phoenix and Postgres. We also use an the Tripdatabase API.
I don't think the architecture will be much more complicated than that. we might have a look at Elm for frontend features but I don't think it's necessary at this stage.
Otherwise the database structure will be define as the same time as the features.
I think this issue could be close, @markwilliamfirth what do you think?

**Comment by markwilliamfirth** [comment]
Ok to close then - @SimonLab if it gets more complex please consult @nelsonic if you need any help with it. He is booked on for 1.5 days across the two sprints.
