### ISSUE TITLE
Bug: error when creating new user with a password under 6 chars

### ISSUE THREAD

**Issue by Cleop** [dwyl/best-evidence#118]
![image](https://user-images.githubusercontent.com/16775804/29168413-a6eda2b4-7dc6-11e7-8b7a-0eb0fd250193.png)
See: https://github.com/dwyl/best-evidence/blob/301c55c35826f08eedc6c3ea331aeb3ac4226504/web/controllers/user_controller.ex#L19

Is looking for email error instead of password error.

**Comment by ajburls** [comment]
@SimonLab Thanks. App doesn't crash. Now it returns a message "oops something went wrong" if one tries to create a password of less than 6 characters. (This will do but wouldn't it be better if the message said "Please make sure you use at least 6 characters for your password"? or is this complicated?)

**Comment by SimonLab** [comment]
There is also a message to let user know that the email length is invalid. I think it's not very obvious because we have already added a warning on the page which looks similar. The error message are automatically created by the validation system. I'm not sure how easy it is to customise it:
![warning-length-emil](https://user-images.githubusercontent.com/6057298/29670637-2c8d99f6-88df-11e7-9473-cbdb878edfc0.png)

**Comment by ajburls** [comment]
@SimonLab Thanks for fast response, Simon. I will close this issue then as I think we have much more important ones to deal with.
