### ISSUE TITLE
Allowing users to save specific articles

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/best-evidence#142]
TBC

This would imply adding a page to allow them to review these as well

**Comment by markwilliamfirth** [comment]
@ajburls please can you assign a priority label to this?

**Comment by SimonLab** [comment]
I'm not sure I understand this issue. At the moment we are saving some information (title, url, tripdatabase_id) about what we call publication (which are the evidences searched). Each time a user click on a publication these information will be saved into the database if they do not exist yet:
![image](https://user-images.githubusercontent.com/6057298/29713065-d9f02716-8994-11e7-9c7e-f4c34bcf43ce.png)

@markwilliamfirth are your referring to these items, or is it another feature?

**Comment by markwilliamfirth** [comment]
@SimonLab this is a different feature that comes from the original scope

The user has the ability to "save" a publication that will appear on a page of saved publications

This is similar to the way a bookmark functions on a browser

It might not be needed anymore

@ajburls please can you assign a priority or close this issue if it is no longer needed?

**Comment by SimonLab** [comment]
Thanks for confirming it's another feature @markwilliamfirth . I haven't seen this feature on the original wireframes of @harrygfox and I don't remember to have detailed the user flow for this feature yet but happy to go over this.

**Comment by markwilliamfirth** [comment]
<img width="772" alt="screen shot 2017-08-25 at 15 10 08" src="https://user-images.githubusercontent.com/5732209/29713510-83bd0572-89a7-11e7-804e-bbc5b48468fe.png">

@SimonLab it may well be that during Harry's and Amanda's discussions they decided not to proceed with it

@ajburls to confirm priority or close if no longer needed

**Comment by ajburls** [comment]
@markwilliamfirth @SimonLab I am also now sure what the original issue reference. The critical functionality I wanted of knowing what you have looked at is covered by the paling of links and the existence of notes.

Other functionality I know I wanted was to be able to get the actual article not just the abstract etc. via, for example, Sci-Hub but I think that is well beyond the scope of the MVP (and would probably give City's PTB kerniptions because of its clandestine nature). So we can dismiss that for now.

Other functionality I also mentioned was a starring of particular papers of high interest to highlight them for the future and this may be what was referenced. Cant remember whether this was mentioned in proposal or not but if it didn't add too much time it would be nice to have now but it would be a low priority 3. 

I will add this as an issue to make it clear and close this issue.
