### ISSUE TITLE
Bug: Internal Server Error clicking on blank note from Recent Searches

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/best-evidence#214]
<img width="753" alt="screen shot 2017-09-07 at 09 19 15" src="https://user-images.githubusercontent.com/5732209/30153197-b275b3cc-93ad-11e7-83bd-02247a6f0871.png">

Internal server error appears when I click on a blank saved note next to a recent search on the main page

**Comment by SimonLab** [comment]
Error:
![image](https://user-images.githubusercontent.com/6057298/30175431-684697e6-93f6-11e7-9c44-556ca2c06888.png)

This is cause by the call of the function ```URI.encode``` on the note. The note is currently empty (value nil)
https://github.com/dwyl/best-evidence/blob/458a2ed2b23427fb5297841b329f0261a4c764d4/web/controllers/note_search_controller.ex#L23

![image](https://user-images.githubusercontent.com/6057298/30175517-b345ddc4-93f6-11e7-854a-8170d850a942.png)

One solution is to only apply ```URI.encode``` if the note is different to ```nil``` otherwise we can just define the body of the message as an empty string (or no body at all :thinking: )

**Comment by ajburls** [comment]
I am not getting this error now.Thanks.
