### ISSUE TITLE
Notes

### ISSUE THREAD

**Issue by markwilliamfirth** [dwyl/best-evidence#22]
Starting **only** with the **blank field for notes**.

**Search functionality**
- [x] Functionality to create a new note about a search (T1d)
- [x] Show searches with notes on all notes page
- [x] A view of an existing note (on which you can also edit and save the note)
- [x] 'Add a note' icon next to instances of search history in 'recent searches' section (T1.5h)
- [x] 'Add a note' icon next to searches in the history page

**Publication functionality**
- [x] Functionality to create a new note about a publication(T2h)
- [x] Show publications with notes on all notes page
- [x] A view of an existing publication note (on which you can edit/ save)
- [x] Users can create notes (with an icon next to each publication) on the search results page. (T2h + T1.5h styling)
- [x] 'Add a note' icon next to publications in the history page
<img src="https://user-images.githubusercontent.com/16775804/28274410-bad27faa-6b08-11e7-947c-4d4de88a1a0c.png" width=230px />
<img src="https://user-images.githubusercontent.com/16775804/28274369-9ab66bfa-6b08-11e7-96b9-38d2200f3dd5.png" width=230px />
<img src="https://user-images.githubusercontent.com/16775804/28274292-67510ac2-6b08-11e7-84c0-147cffdfe72f.png" width=230px />
<img src="https://user-images.githubusercontent.com/16775804/28274621-4a2dd23a-6b09-11e7-9112-a76765da8d1a.png" width=230px />

**Comment by Cleop** [comment]
Possible note symbols:
![image](https://user-images.githubusercontent.com/16775804/29267913-a05f0982-80e2-11e7-8c53-70407d4bf156.png)
![image](https://user-images.githubusercontent.com/16775804/29267925-af2a15ba-80e2-11e7-8223-5bf2fbe76e69.png)

**Comment by ajburls** [comment]
@cleop We need three messages: Note symbol that indicates there is nothing written, note symbol that indicates some notes but not complete, completed note.

Could be achieved by changing colour or by symbols for example yours above could have third one with lines across indicating note written

**Comment by markwilliamfirth** [comment]
Linked to https://github.com/dwyl/best-evidence/issues/122

**Comment by markwilliamfirth** [comment]
@ajburls something like this for a completed note?

![completed note](https://user-images.githubusercontent.com/5732209/29275543-65acac6a-8103-11e7-966d-6782013645c2.png)

**Comment by ajburls** [comment]
@markwilliamfirth @Cleop  Yes - looks good

**Comment by ajburls** [comment]
@SimonLab Simon, I like that we can now write notes on papers and I think it is very good. All my three machines are getting same history and notes. 

With respect to the database structure: we need to have the notes for a search or a paper linked. Also, if same search is run again (especially on same day) to get back to the search to find another paper, I think it would be better if it appeared as one search rather than several. The only way to show all papers opened under a particular search at the moment is to follow the back arrow route back to the search but there are multiple other ways to get there. I hope this makes sense. It might make more sense if you see the current screenshot of my today's searches 

![image](https://user-images.githubusercontent.com/30235568/29526820-cae86d86-868e-11e7-9e54-693a493a596d.png)

This then begs the question of dating when a search was done. I think that we might need two dates: Date first searched and date last searched 

The history would show what searched on each date.

**Comment by markwilliamfirth** [comment]
@ajburls please can you test and close this issue if you are happy that the requirements in the top comment have been fulfilled?

We have created a new issue to address your comment above: https://github.com/dwyl/best-evidence/issues/162

**Comment by ajburls** [comment]
@markwilliamfirth Something has gone wrong on this. The version of the app on my Android no longer shows the same history and notes as the desktop,

**Comment by SimonLab** [comment]
@ajburls I saw that there are two email addresses on the database linked to your account, one correct and one with a trailing space at the end. I think there was a typo when you created your account. It might be why the history is different. I've created an issue to make sure to delete white spaces at the end of the email, see #170 which will be resolved soon.

**Comment by ajburls** [comment]
@SimonLab OK that explains that then. Well spotted :-)

@markwilliamfirth re notes at the top it says 
**Functionality to create a new note about a publication(T2h)
 Show publications with notes on all notes page"**
 
Currently, a note on a publication can only be found by going to the history page, as Notes page is only showing notes on searches. I don't know if I am supposed to close this because we have a notes field and make a new issue about them not appearing or whether to keep this open as the notes are not yet doing what it said in first comment.

**Comment by markwilliamfirth** [comment]
@ajburls you're correct

- [ ]  Show publications with notes on all notes page

Doesn't appear to display yet

@SimonLab could you please confirm and let us know a time estimate for this to be resolved?

**Comment by markwilliamfirth** [comment]
Moving this to sprint 3 as there wasn't time to complete this in sprint 2

**Comment by SimonLab** [comment]
This will be fixed with #192 : 
![image](https://user-images.githubusercontent.com/6057298/29994004-84b0cbbe-8fbd-11e7-99b7-fbb0d0a30244.png)

@ajburls when an evidence has a note but not the search term linked to the evidence the edit pencil icon is not shown near the search term, is this ok?

**Comment by ajburls** [comment]
Yes. This is good.

Amanda



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by SimonLab** [comment]
The note page is now ready to be tested @ajburls : the search term and the publications are now displayed on the page.

**Comment by ajburls** [comment]
No, this is not working for me. Only notes on search showing on notes page. I tried deleting the saved on home screen button and going via website to see if this was the issue but it wasn't. However, now app appears as a webpage not as an app as before. Also it no longer recognised me and I had to create new account.I used my previous email address and password and it let me create an identical new account but old history lost.

**Comment by SimonLab** [comment]
Thanks for testing @ajburls , I think you saw that I reset the database and that's why you had to create an account. You might need to create a new one again as I wanted to be sure that the database was clean so I reset it again. Could you please try again to see if the notes for the publications are displayed, this should be ok now. Thanks

**Comment by ajburls** [comment]
@SimonLab Notes page now showing notes for both search and paper. The completed and open notes icons also showing. 

Need to link to search and paper as they do in the history, otherwise you can't tell what they are about. Should I close this issue  or will this linking be done as part of this issue?

**Comment by markwilliamfirth** [comment]
@ajburls this has been merged in - please close if it is now satisfactory

**Comment by ajburls** [comment]
😊
