### ISSUE TITLE
Bug Tracking Issue: Unnecessary repeated logins on mobile devices

### ISSUE THREAD

**Issue by ajburls** [dwyl/best-evidence#88]
As a user of the app
I need to be able to access the app from a device such as my mobile phone without constantly having to login
To save time and not add deterent to using app

This was agreed but my phone keeps asking me to login

**Comment by SimonLab** [comment]
I think it might be due to our recent deployment of code on staging. I will do more investigation but I think each time we are going to deploy new code you might have to login again as the application has changed. On production this wouldn't be an issue as the code won't change as often.

**Comment by ajburls** [comment]
Just used app again after closing it and wasn't required to login again so either intermittent fault, fixed fault or due as you hypothesise to an new code deployment.

**Comment by SimonLab** [comment]
Thanks for testing this again. Let's keep this issue open and let's track when the application ask us to login.

**Comment by markwilliamfirth** [comment]
Amanda to be notified when app is redeployed to see if this is the issue

**Comment by markwilliamfirth** [comment]
@ajburls please could you check if this bug is still present?

**Comment by ajburls** [comment]
@markwilliamfirth @SimonLab Histories and notes are now concordant across the apps (Thanks, Simon, for spotting and resolving trailing space issue). However, I still have to login every time I use the app

**Comment by markwilliamfirth** [comment]
@SimonLab this still appears to be an issue, let's ensure we fix it this sprint

**Comment by markwilliamfirth** [comment]
@ajburls we think this issue is due to merging pull requests to the staging app. We merge at least one PR per day, which resets the cookies, which consequently requires users to log in again.

A way to double check if this is what is causing this bug is for us to deploy on the production app and to ask you to login there and test if it is still an issue. We don't deploy on production at the moment so theoretically there should be no issues and logins should be automatic.

Please note that if we do this the production database will be wiped as we haven't written migration scripts for the data yet - once the app is in production with real users, time can be put into writing migration scripts, but before we have real users, that time is best spent on features.

Please can you confirm if you're happy or not for us to proceed with the production deployment and wiping of the production database?

**Comment by ajburls** [comment]
Yes. I think we will want to wipe the database at the end of Sprint 3 anyway as Jose and I and others are adding nonsense anyway to test things.

**Comment by markwilliamfirth** [comment]
Next steps:

- [ ] @SimonLab to push app to production site

- [ ] @ajburls to log into production app and check if log in issue persists

**Comment by ajburls** [comment]
@markwilliamfirth is production app now going to be via bestevidence.info?

**Comment by markwilliamfirth** [comment]
@ajburls yes http://bestevidence.info/ links to http://best-evidence-app.herokuapp.com/

Both links will continue to work - both are the same app - the production app.

You can continue to access staging via https://best-evidence-staging.herokuapp.com/

Linked to #30

**Comment by SimonLab** [comment]
@markwilliamfirth @ajburls I will deploy the application to production soon, I just want to finish #165 and #162 first

**Comment by markwilliamfirth** [comment]
@SimonLab has the app been deployed to production now?

**Comment by ajburls** [comment]
I think this is now working OK but am only testing on "staging"
